model_params:
    loss: 'kld' # or 'kld'
    lr: 0.0007083
    encoder_name: 'efficientnet-b4' 
    warmup_duration: 5
    warmup_start_factor: 0.0001
    cos_annealing_eta_min: 0.00005
    threshold_scale_true_mask: 3
    threshold_scale_pred_mask: 4.752
mask_params:
    min_val: 0.0
    coeff: 35531.427
    standard_mask_scale: 30000
augmentation_params:
    image_height: 512
    image_width: 224
    p_horizontal_flip: 0.5
    p_vertical_flip: 0.277
    p_rotate: 0.735
    limit_rotate: 30
    blur_limit: [1, 3]
    p_blur: 0.25
    p_gauss_noise: 0.15
    p_random_brightness_contrast: 0.5
    p_rgb_shift: 0.5
    r_shift_limit: 15
    g_shift_limit: 15
    b_shift_limit: 15
    p_color_jitter: 0.703
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
    p_to_gray: 0.1
training_params:
    batch_size: 8
    max_epochs: 150
    devices: [0]
    accelerator: 'gpu'
    patience: 20
    num_workers: 23
    local_log: True
infer_params:
    in_dir_path: '/home/jupyter-igor_busov/detection/data/holdout'
    out_dir_path: '/home/jupyter-igor_busov/detection/infer_example'
    model_path: '/home/jupyter-igor_busov/detection/models/unet_kld_final.ckpt'
    segmentation_mask_dir_path: '/home/jupyter-igor_busov/detection/data/holdout_mask_segmentation'
    batch_size: 8
    device: 'cuda'
    num_workers: 23
test_params:
    model_path: '/home/jupyter-igor_busov/detection/models/unet_kld_final.ckpt'
    out_json_file_name: '/home/jupyter-igor_busov/detection/test_result/holdout_res.json'
    batch_size: 8
    device: 'cuda'
    num_workers: 23
pathes:
    wandb_project: 'final_detection_models'
    wandb_name: 'ce'
    dirpath_models_saving: '/home/jupyter-igor_busov/detection/models'
    train_path: '/home/jupyter-igor_busov/detection/data/train'
    # test_path: '/home/jupyter-igor_busov/detection/data/test'
    val_path: '/home/jupyter-igor_busov/detection/data/val'
    test_path: '/home/jupyter-igor_busov/detection/data/holdout'
    train_mask_path: '/home/jupyter-igor_busov/detection/data/train_mask'
    # test_mask_path: '/home/jupyter-igor_busov/detection/data/test_mask'
    val_mask_path: '/home/jupyter-igor_busov/detection/data/val_mask'
    test_mask_path: '/home/jupyter-igor_busov/detection/data/holdout_mask'
    train_mask_segment_path: '/home/jupyter-igor_busov/detection/data/train_mask_segmentation'
    # test_mask_segment_path: '/home/jupyter-igor_busov/detection/data/test_mask_segmentation'
    val_mask_segment_path: '/home/jupyter-igor_busov/detection/data/val_mask_segmentation'
    test_mask_segment_path: '/home/jupyter-igor_busov/detection/data/holdout_mask_segmentation'
    train_json_coords_path: '/home/jupyter-igor_busov/detection/data/centers/train.json'
    val_json_coords_path: '/home/jupyter-igor_busov/detection/data/centers/val.json'
    # test_json_coords_path: '/home/jupyter-igor_busov/detection/data/centers/test.json'
    test_json_coords_path: '/home/jupyter-igor_busov/detection/data/centers/holdout.json'
    standard_mask_path: '/home/jupyter-igor_busov/detection/detection_models/standard_normal_mask.npy'
hyperparameters:
    encoders: ['efficientnet-b3', 'efficientnet-b4', 'mit_b2', 'mit_b1',
               'timm-resnest26d', 'timm-regnetx_032', 'timm-res2next50',
               'timm-gernet_m','timm-efficientnet-b4', 'timm-efficientnet-b3']
    lr: [0.00001, 0.001]
    cos_annealing_eta_min: [0.000001, 0.00005]
    thr_scale_pred_msk: [2, 9]
    coeff: [5000, 500000]
    epoches: 30
    n_initial_points: 15
    n_calls: 30
    losses: ['kld', 'ce']
    